[package]
name = "json-patch"
version = "0.2.5"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
categories = []
keywords = ["json", "json-patch"]
description = "RFC 6902, JavaScript Object Notation (JSON) Patch"
repository = "https://github.com/idubrov/json-patch"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[features]
default = ["diff"]
nightly = []
diff = ["treediff"]

[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx.git" }

sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx.git" }

treediff = { git = "https://github.com/enigmampc/treediff-rs.git", rev = "3.0.1-sgx-1.1.0", features = ["with-serde-json"], optional = true }

[dev-dependencies]
rand = "0.5.0"
